version: '3.8'

services:

  db:
    image: postgres:12.0-alpine
    container_name: postgres_t
    volumes:
      - ./schema_design/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5434:5432"
    labels:
      reproxy.enabled: false

  service:
    build:
      context: ./django_api
      dockerfile: Dockerfile
    container_name: service_t
    restart: always
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
      - ./django_api/uwsgi/uwsgi.ini:/opt/app/uwsgi.ini
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - UWSGI_PROCESSES=1
      - UWSGI_THREADS=16
      - UWSGI_HARAKIRI=240
    labels:
        reproxy.server: '*'
        reproxy.route: '^/(.*)'
        reproxy.dest: '/$$1'

  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reproxy.yml:/reproxy.yml
      - static_value:/web/static
      - media_value:/web/media
    environment:
      - TZ=Europe/Moscow
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - DEBUG=true
      - FILE_ENABLED=true
      - FILE_NAME=/reproxy.yml

#
#  swagger:
#    image: swaggerapi/swagger-ui
#    volumes:
#      - ./docs/openapi.yaml:/swagger.yaml
#    environment:
#      SWAGGER_JSON: /swagger.yaml
#    depends_on:
#      - nginx
#    ports:
#      - "8082:8080"

volumes:
  postgres_data:
  static_value:
  media_value:
